services:
  tg_bot:
    build: ./tg_bot
    env_file:
      - ./tg_bot/.env
    restart: unless-stopped
  fastapi_app:
    build: ./fastapi_app
    ports:
      - "8000:8000"
    restart: unless-stopped